# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0002_auto_20180106_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='<No course name>', max_length=199),
            preserve_default=False,
        ),
    ]
