# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0003_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('BMT', 'Biomedishe Technologie'), ('BK', 'boukunde'), ('ESoE', 'Eindhoven School of education'), ('EE', 'Electrical Engineering'), ('ID', 'Industrial design'), ('IEID', 'Industrial Engineering & Innovation Sciences'), ('ST', 'Scheikundige technologie'), ('TN', 'technishe natuurkunde'), ('wbtk', 'werktuigboukunde'), ('WI', 'wiskunde & informatica')], default='BK', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('sfs', 'Software Science'), ('ws', 'Web Science'), ('ee', 'Electrical Engineering'), ('id', 'Industrial Design')], max_length=16),
        ),
    ]
