# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0007_auto_20180111_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratingOverall',
            field=models.IntegerField(default=5),
        ),
    ]
