# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0008_review_ratingoverall'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='averageRating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
