# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0010_course_reviewnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='thumbsDown',
            field=models.ManyToManyField(related_name='thumbsDown', to='tureview.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbsUp',
            field=models.ManyToManyField(related_name='thumbsUp', to='tureview.Student'),
        ),
    ]
