# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0012_auto_20180115_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
