# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tureview', '0013_auto_20180115_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratingDiff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratingInf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratingOverall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratingRele',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratingTime',
            field=models.IntegerField(default=0),
        ),
    ]
